apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scmvanilla
resources:
#  - namespace.yaml
  - siebel.yaml
  - siebel-config.yaml
  - siebel-gateway.yaml
  - siebel-monitor.yaml
  - siebel-artifacts.yaml