apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: scmvanilla-nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '180'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '180'
    nginx.ingress.kubernetes.io/session-cookie-change-on-failure: 'false'
    nginx.ingress.kubernetes.io/session-cookie-max-age: '172800'
    nginx.ingress.kubernetes.io/session-cookie-name: siebel-app-ingress
  name: siebel-app-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: quantum
            port:
              number: 4430
        path: /siebel/app/dav/enu
        pathType: Prefix
      - backend:
          service:
            name: quantum
            port:
              number: 4430
        path: /siebel/v1.0
        pathType: Prefix
      - backend:
          service:
            name: quantum
            port:
              number: 4430
        path: /eai_enu
        pathType: Prefix
      - backend:
          service:
            name: quantum
            port:
              number: 4430
        path: /siebel/app/CustAppSvcs/enu
        pathType: Prefix
      - backend:
          service:
            name: quantum
            port:
              number: 4430
        path: /siebel/app/eai_anon/enu
        pathType: Prefix
      - backend:
          service:
            name: quantum
            port:
              number: 4430
        path: /siebel/v1.0
        pathType: Prefix
      - backend:
          service:
            name: quantum
            port:
              number: 4430
        path: /eai_enu
        pathType: Prefix
      - backend:
          service:
            name: quantum
            port:
              number: 4430
        path: /siebel/app/eai/enu
        pathType: Prefix
      - backend:
          service:
            name: quantum
            port:
              number: 4430
        path: /siebel/v1.0
        pathType: Prefix
      - backend:
          service:
            name: quantum
            port:
              number: 4430
        path: /eai_enu
        pathType: Prefix
      - backend:
          service:
            name: quantum
            port:
              number: 4430
        path: /siebel/app/webtools/enu
        pathType: Prefix
      - backend:
          service:
            name: quantum
            port:
              number: 4430
        path: /siebel/app/epublicsector/enu
        pathType: Prefix
      - backend:
          service:
            name: quantum
            port:
              number: 4430
        path: /siebel/app/epsportal/enu
        pathType: Prefix
      - backend:
          service:
            name: quantum
            port:
              number: 4430
        path: /siebel/app/pssservice/enu
        pathType: Prefix
      - backend:
          service:
            name: quantum
            port:
              number: 4430
        path: /siebel/migration
        pathType: Prefix
      - backend:
          service:
            name: quantum
            port:
              number: 4430
        path: /siebel/sma
        pathType: Prefix
  tls:
  - hosts:
    - scmvanilla-ingress-nginx-controller
    secretName: lb-tls-certificate
